# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PYPI Publish

on:
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  test:
    uses: ./.github/workflows/test.yml
  pypi-publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: pdm-project/setup-pdm@v3
      with:
        version: 'head'
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup & Publish
      run: |
        pdm install
        pdm publish
